version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_test
    ports:
      - "6379:6379"
    networks:
      - cache_network

networks:
  cache_network:
    driver: bridge
